name: phoenix
description: A Dart wrapper for phoenix framework channels
version: 0.0.8
homepage: https://github.com/sclee15/phoenix_channel
author: S.-C. Lee <consoledir@outlook.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1