name: phoenix
description: A Dart wrapper for phoenix framework channels
version: 0.0.8
homepage: https://github.com/sclee15/phoenix_channel
author: S.-C. Lee <consoledir@outlook.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  js: any